runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /app
  static_dir: app
- url: .*
  script: susyandsteve.app

libraries:
- name: webapp2
  version: latest
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest
